### PR TITLE
initPID() setup wrong data.

### PR DESCRIPTION
**Pull request by NixToDo**
initPID() was called before the data of variable "cfg" was set form the EEPROM data through initEEPROM(). So wrong values were written into the variables "pidRoll", "pidPitch", "pidYaw" and "pidAltHold".

### CODE REVIEW

**Comment by Lauszus** [comment]
No, as initPID just initialises the pointers: https://github.com/Lauszus/LaunchPadFlightController/blob/master/src/PID.h#L34, so the order does not matter.

Btw if you want to send a pull request for just one commit you need to create separate branch with just that commit.

**Comment by NixToDo** [comment]
Oh, sorry. I want to add only the PID issue, not all of my changes.

**Comment by Lauszus** [comment]
@NixToDo no problem. I would recommend the following GUI if you are new to git: https://www.sourcetreeapp.com/.

Btw did you understand why the order was not a bug?

**Comment by Lauszus** [comment]
@NixToDo also I saw this commit: https://github.com/NixToDo/LaunchPadFlightController/commit/8fe9f0c77887bf2de1ba72e587eaec3c0420c6ef. It looks like you had some issues with 4s not being enough? If so I would be happy to merge a PR with the time set to 6s :)

**Pull request closed without merging**
